# Generated by Django 3.0.8 on 2020-08-03 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCR_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftp_ip', models.CharField(max_length=50, verbose_name='IP của FTP')),
                ('ftp_port', models.IntegerField(default=0, verbose_name='Port của FTP')),
                ('ftp_user', models.CharField(max_length=50, verbose_name='Tài khoản đăng nhập FTP')),
                ('ftp_pwd', models.CharField(max_length=50, verbose_name='Mật khẩu')),
                ('api_user', models.CharField(max_length=50, verbose_name='Tài khoản đăng nhập API')),
                ('api_pwd', models.CharField(max_length=50, verbose_name='Mật khẩu')),
                ('is_public_ftp', models.BooleanField(blank=True, default=0, null=True, verbose_name='La FTP public')),
            ],
            options={
                'verbose_name': 'Cấu hình chung',
                'verbose_name_plural': 'Cấu hình chung',
            },
        ),
        migrations.CreateModel(
            name='OCR_Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_info', models.TextField(blank=True, null=True, verbose_name='Thông tin client')),
                ('folder', models.TextField(max_length=1000, verbose_name='Đường dẫn làm việc')),
                ('create_time', models.DateField(blank=True, null=True, verbose_name='Thời gian khởi tạo')),
            ],
            options={
                'verbose_name': 'Lưu thư mục làm việc tạm của user',
                'verbose_name_plural': 'Lưu thư mục làm việc tạm của user',
            },
        ),
        migrations.CreateModel(
            name='OCR_Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=2000, verbose_name='Tên máy API OCR')),
                ('url_api', models.CharField(max_length=2000, verbose_name='Link API OCR')),
                ('url_callback', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Link Callback của API OCR Master')),
                ('api_user', models.CharField(max_length=50, verbose_name='Tài khoản đăng nhập API')),
                ('api_pwd', models.CharField(max_length=50, verbose_name='Mật khẩu')),
                ('is_master', models.BooleanField(blank=True, default=0, null=True, verbose_name='Là API OCR Master')),
                ('is_active', models.BooleanField(blank=True, default=0, null=True, verbose_name='Đang hoạt động')),
                ('time_avg_page', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Thời gian giây trung bình 1 trang')),
                ('waiting_page', models.IntegerField(blank=True, default=0, null=True, verbose_name='Số trang chờ xử lý')),
                ('cpu_no', models.IntegerField(blank=True, default=0, null=True, verbose_name='Số CPU cores')),
            ],
            options={
                'verbose_name': 'Các Node chạy API OCR',
                'verbose_name_plural': 'Các Node chạy API OCR',
            },
        ),
        migrations.CreateModel(
            name='OCR_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_ocr', models.TextField(verbose_name='Nội dung cấu hình OCR')),
                ('ftp_path', models.CharField(max_length=2000, verbose_name='Thư mục FTP')),
                ('file_ocr', models.CharField(max_length=2000, verbose_name='File yêu cầu OCR gốc')),
            ],
            options={
                'verbose_name': 'Lịch sử yêu cầu OCR',
                'verbose_name_plural': 'Lịch sử yêu cầu OCR',
            },
        ),
        migrations.CreateModel(
            name='OCR_NodeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_ocr_input', models.CharField(max_length=2000, verbose_name='File OCR đầu vào')),
                ('file_ocr_output', models.CharField(max_length=2000, verbose_name='File OCR đầu ra')),
                ('file_ocr_pages', models.IntegerField(default=0, verbose_name='Tổng số trang')),
                ('file_ocr_page_start', models.IntegerField(default=0, verbose_name='Số trang bat dau')),
                ('file_ocr_page_size', models.IntegerField(default=0, verbose_name='Số trang size')),
                ('status', models.IntegerField(blank=True, default=0, null=True, verbose_name='Trạng thái')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Thông tin lỗi')),
                ('access_time', models.DateField(blank=True, null=True, verbose_name='Thời gian xử lý')),
                ('node_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocrapi.OCR_Nodes', verbose_name='Node API OCR thực hiện')),
                ('request_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocrapi.OCR_Request', verbose_name='Yêu cầu OCR')),
            ],
            options={
                'verbose_name': 'Xử lý OCR song song',
                'verbose_name_plural': 'Xử lý OCR song song',
            },
        ),
    ]
